site_name: Break Through Cancer Data Reference 
nav:
    - '  ':  index.md
    - FAQ:   faq.md
    - '  ':  about.md
    - '  ':  relnotes.md

docs_dir: content
site_dir: dataref

extra_css:
    - extra.css
