site_name: Break Through Cancer Data Reference 
nav:
    - '  ':  index.md
    - FAQ:   faq.md
    - '  ':  about.md

docs_dir: content
site_dir: dataref

extra_css:
    - extra.css

markdown_extensions:
  - pymdownx.superfences:
    custom_fences:
      - name: csv-path
        class: csv-path
        format: !!python/name:tools.pymdownx_md_render.md_csv_path_render
